#ifndef TPFINALPDM_TRABAJOFINALPDM_INC_AVL_MAIN_H_
#define TPFINALPDM_TRABAJOFINALPDM_INC_AVL_MAIN_H_

#define TICK_RATE		1 // Default 1ms

#define TICK_RATE_MIN	1  // ms
#define TICK_RATE_MAX	50 // ms

typedef enum
{
	MENU,
	OTHER_TASKS,
}stateMain_t;

#endif // TPFINALPDM_TRABAJOFINALPDM_INC_AVL_MAIN_H_
